In [1]:
from neural_net import *
import numpy

In [2]:
n,k = 300,2
X = numpy.random.uniform(-1,1,size=(n,k))
y = (X.sum(axis=1) < numpy.random.uniform(.3,.37,(len(X),))).reshape(-1,1)+0

In [3]:
y_one_hot = pipeline.onehot(y)
y_one_hot

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0,

In [4]:
W = numpy.zeros((X.shape[1]+1,2))
W

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
W = numpy.zeros((X.shape[1],2))
Softmax = lambda W,X : numpy.exp(X.dot(W))/numpy.exp(X.dot(W)).sum(axis=1).reshape(-1,1)
Softmax(W,X)

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5,

In [6]:
J = 1/len(X)*X.T.dot(Softmax(W,X)-y_one_hot)
J

array([[-0.13230135,  0.13230135],
       [-0.16168278,  0.16168278]])

In [4]:
ann = architecture.Sequential(
     [

       layers.Fullyconnected(n_in=2,n_out=2,init_method=init_funcs.zeros) ,
       layers.Activation(activation.Softmax)


    ],
    cost = cost.CrossEntropy
)

In [5]:
p = ann.eval(X)
p

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5,

In [6]:
ann['cost'](y_one_hot,p).out()

0.6931471805599453

In [7]:
g1 = ann['cost'](y_one_hot,p).prime()
g1

array([[ 2., -2.],
       [ 2., -2.],
       [ 2., -2.],
       [ 2., -2.],
       [-2.,  2.],
       [-2.,  2.],
       [ 2., -2.],
       [ 2., -2.],
       [-2.,  2.],
       [ 2., -2.],
       [ 2., -2.],
       [ 2., -2.],
       [ 2., -2.],
       [-2.,  2.],
       [ 2., -2.],
       [ 2., -2.],
       [ 2., -2.],
       [-2.,  2.],
       [ 2., -2.],
       [ 2., -2.],
       [-2.,  2.],
       [-2.,  2.],
       [ 2., -2.],
       [ 2., -2.],
       [ 2., -2.],
       [ 2., -2.],
       [ 2., -2.],
       [ 2., -2.],
       [-2.,  2.],
       [-2.,  2.],
       [ 2., -2.],
       [ 2., -2.],
       [ 2., -2.],
       [-2.,  2.],
       [-2.,  2.],
       [-2.,  2.],
       [-2.,  2.],
       [-2.,  2.],
       [ 2., -2.],
       [-2.,  2.],
       [ 2., -2.],
       [ 2., -2.],
       [-2.,  2.],
       [-2.,  2.],
       [ 2., -2.],
       [-2.,  2.],
       [-2.,  2.],
       [ 2., -2.],
       [-2.,  2.],
       [ 2., -2.],
       [ 2., -2.],
       [-2.,  2.],
       [ 2.,

In [8]:
g2 = ann['steps'][-1].func.prime()
g2

array([[0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25, 0.25],
       [0.25,

In [9]:
g3 = ann['steps'][-2].func.prime()
g3

array([[-0.56460905,  0.06185348,  1.        ],
       [ 0.43374734, -0.81200515,  1.        ],
       [-0.34451669, -0.52033586,  1.        ],
       [-0.32801609, -0.38891069,  1.        ],
       [ 0.00983587,  0.70832236,  1.        ],
       [ 0.04084632,  0.54432458,  1.        ],
       [-0.20026455,  0.0932692 ,  1.        ],
       [-0.78455721, -0.03813314,  1.        ],
       [ 0.8974411 ,  0.54801976,  1.        ],
       [-0.03140259, -0.73920339,  1.        ],
       [-0.32958196,  0.24195267,  1.        ],
       [-0.33294585, -0.61420714,  1.        ],
       [-0.79144247, -0.54917381,  1.        ],
       [ 0.58970237,  0.90057154,  1.        ],
       [ 0.1917572 , -0.28374447,  1.        ],
       [-0.7472671 ,  0.21961887,  1.        ],
       [-0.38382436, -0.88954038,  1.        ],
       [ 0.36347417,  0.91273416,  1.        ],
       [ 0.14757534, -0.20634642,  1.        ],
       [-0.94353245,  0.67726615,  1.        ],
       [ 0.93192744,  0.68708183,  1.   

In [10]:
g3.shape

(300, 3)

In [11]:
g2*g1

array([[ 0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [ 0.5, -0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [ 0.5,

In [12]:
g3.T.dot(g2*g1)/ann['steps'][-2].func.n()

array([[-0.13575512,  0.13575512],
       [-0.16006827,  0.16006827],
       [ 0.15      , -0.15      ]])

In [36]:
k=2
W = numpy.zeros((X.shape[1]+1,k))
Softmax = lambda W,X : numpy.exp(X.dot(W))/numpy.exp(X.dot(W)).sum(axis=1).reshape(-1,1)
J_W = lambda W,X : 1/n*X.T.dot(Softmax(W,X)-y_one_hot)

for _ in range(100):
    W -= J_W(W,numpy.c_[X,numpy.ones((n,1))]) 

In [37]:
W

array([[ 2.59144936, -2.59144936],
       [ 2.69676793, -2.69676793],
       [-1.01655813,  1.01655813]])

In [38]:
ann.train(X,y_one_hot,epochs=100)

100%|██████████| 100/100 [00:00<00:00, 997.18it/s]


In [40]:
ann['steps'][-2].func.W

array([[ 2.60202023, -2.60202023],
       [ 2.70715318, -2.70715318],
       [-1.01995539,  1.01995539]])

In [15]:
Softmax(W,numpy.c_[X,numpy.ones((n,1))])

array([[0.39329193, 0.60670807],
       [0.39122029, 0.60877971],
       [0.36352008, 0.63647992],
       [0.37435836, 0.62564164],
       [0.48236492, 0.51763508],
       [0.47136845, 0.52863155],
       [0.4195758 , 0.5804242 ],
       [0.3716317 , 0.6283683 ],
       [0.52974125, 0.47025875],
       [0.36698523, 0.63301477],
       [0.42262005, 0.57737995],
       [0.35731698, 0.64268302],
       [0.33387841, 0.66612159],
       [0.53703606, 0.46296394],
       [0.41610758, 0.58389242],
       [0.39350979, 0.60649021],
       [0.33425854, 0.66574146],
       [0.522706  , 0.477294  ],
       [0.41921644, 0.58078356],
       [0.41596469, 0.58403531],
       [0.54313944, 0.45686056],
       [0.5452536 , 0.4547464 ],
       [0.44123135, 0.55876865],
       [0.39763736, 0.60236264],
       [0.41884987, 0.58115013],
       [0.43450872, 0.56549128],
       [0.37496332, 0.62503668],
       [0.4103104 , 0.5896896 ],
       [0.51141145, 0.48858855],
       [0.46093228, 0.53906772],
       [0.

In [27]:
ann = architecture.Sequential(
     [

       layers.Fullyconnected(n_in=2,n_out=2,init_method=init_funcs.zeros) ,
       layers.Activation(activation.Softmax)


    ],
    cost = cost.CrossEntropy
)
p=ann.eval(X)

In [28]:
c = ann['cost'](y_one_hot,p)

In [29]:
g1=c.prime()

In [30]:
g2 = ann['steps'][-1].func.grad(g1)

In [31]:
g3 = ann['steps'][-2].func.grad(g2)

In [32]:
ann['steps'][-2].func.W

array([[ 0.13575512, -0.13575512],
       [ 0.16006827, -0.16006827],
       [-0.15      ,  0.15      ]])

In [24]:
ann['steps'][-2].func.out()

array([[-2.16747791e-01,  2.16747791e-01],
       [-2.21092836e-01,  2.21092836e-01],
       [-2.80059164e-01,  2.80059164e-01],
       [-2.56782124e-01,  2.56782124e-01],
       [-3.52847976e-02,  3.52847976e-02],
       [-5.73258110e-02,  5.73258110e-02],
       [-1.62257499e-01,  1.62257499e-01],
       [-2.62611565e-01,  2.62611565e-01],
       [ 5.95527986e-02, -5.95527986e-02],
       [-2.72586067e-01,  2.72586067e-01],
       [-1.56013493e-01,  1.56013493e-01],
       [-2.93514177e-01,  2.93514177e-01],
       [-3.45347668e-01,  3.45347668e-01],
       [ 7.42080425e-02, -7.42080425e-02],
       [-1.69386464e-01,  1.69386464e-01],
       [-2.16291322e-01,  2.16291322e-01],
       [-3.44493309e-01,  3.44493309e-01],
       [ 4.54432548e-02, -4.54432548e-02],
       [-1.62995406e-01,  1.62995406e-01],
       [-1.69680542e-01,  1.69680542e-01],
       [ 8.64939198e-02, -8.64939198e-02],
       [ 9.07555497e-02, -9.07555497e-02],
       [-1.18083084e-01,  1.18083084e-01],
       [-2.

In [33]:
Softmax(ann['steps'][-2].func.W,ann['steps'][-2].func.Xb())

array([[0.39329193, 0.60670807],
       [0.39122029, 0.60877971],
       [0.36352008, 0.63647992],
       [0.37435836, 0.62564164],
       [0.48236492, 0.51763508],
       [0.47136845, 0.52863155],
       [0.4195758 , 0.5804242 ],
       [0.3716317 , 0.6283683 ],
       [0.52974125, 0.47025875],
       [0.36698523, 0.63301477],
       [0.42262005, 0.57737995],
       [0.35731698, 0.64268302],
       [0.33387841, 0.66612159],
       [0.53703606, 0.46296394],
       [0.41610758, 0.58389242],
       [0.39350979, 0.60649021],
       [0.33425854, 0.66574146],
       [0.522706  , 0.477294  ],
       [0.41921644, 0.58078356],
       [0.41596469, 0.58403531],
       [0.54313944, 0.45686056],
       [0.5452536 , 0.4547464 ],
       [0.44123135, 0.55876865],
       [0.39763736, 0.60236264],
       [0.41884987, 0.58115013],
       [0.43450872, 0.56549128],
       [0.37496332, 0.62503668],
       [0.4103104 , 0.5896896 ],
       [0.51141145, 0.48858855],
       [0.46093228, 0.53906772],
       [0.

In [35]:
ann.eval(X)

array([[0.39329193, 0.60670807],
       [0.39122029, 0.60877971],
       [0.36352008, 0.63647992],
       [0.37435836, 0.62564164],
       [0.48236492, 0.51763508],
       [0.47136845, 0.52863155],
       [0.4195758 , 0.5804242 ],
       [0.3716317 , 0.6283683 ],
       [0.52974125, 0.47025875],
       [0.36698523, 0.63301477],
       [0.42262005, 0.57737995],
       [0.35731698, 0.64268302],
       [0.33387841, 0.66612159],
       [0.53703606, 0.46296394],
       [0.41610758, 0.58389242],
       [0.39350979, 0.60649021],
       [0.33425854, 0.66574146],
       [0.522706  , 0.477294  ],
       [0.41921644, 0.58078356],
       [0.41596469, 0.58403531],
       [0.54313944, 0.45686056],
       [0.5452536 , 0.4547464 ],
       [0.44123135, 0.55876865],
       [0.39763736, 0.60236264],
       [0.41884987, 0.58115013],
       [0.43450872, 0.56549128],
       [0.37496332, 0.62503668],
       [0.4103104 , 0.5896896 ],
       [0.51141145, 0.48858855],
       [0.46093228, 0.53906772],
       [0.

In [ ]:
g1 = ann['cost'](y_one_hot,p).prime()
g1

In [101]:
p=ann.eval(X)
p

array([[0.53896104, 0.46103896],
       [0.6262601 , 0.3737399 ],
       [0.63506148, 0.36493852],
       [0.50523822, 0.49476178],
       [0.57146332, 0.42853668],
       [0.65617537, 0.34382463],
       [0.62630419, 0.37369581],
       [0.61025304, 0.38974696],
       [0.56135797, 0.43864203],
       [0.44457135, 0.55542865],
       [0.6234743 , 0.3765257 ],
       [0.65138293, 0.34861707],
       [0.54463684, 0.45536316],
       [0.61028669, 0.38971331],
       [0.60702947, 0.39297053],
       [0.60800229, 0.39199771],
       [0.5412271 , 0.4587729 ],
       [0.63297981, 0.36702019],
       [0.52307336, 0.47692664],
       [0.56237107, 0.43762893],
       [0.54682844, 0.45317156],
       [0.54231878, 0.45768122],
       [0.57024373, 0.42975627],
       [0.54322642, 0.45677358],
       [0.65036258, 0.34963742],
       [0.66037061, 0.33962939],
       [0.51465741, 0.48534259],
       [0.55010239, 0.44989761],
       [0.513022  , 0.486978  ],
       [0.54945465, 0.45054535],
       [0.

In [ ]:
array([[0.46103896, 0.53896104],
       [0.3737399 , 0.6262601 ],
       [0.36493852, 0.63506148],
       [0.49476178, 0.50523822],
       [0.42853668, 0.57146332],
       [0.34382463, 0.65617537],
       [0.37369581, 0.62630419],
       [0.38974696, 0.61025304],

In [103]:
ann.out

array([[0.53896104, 0.46103896],
       [0.6262601 , 0.3737399 ],
       [0.63506148, 0.36493852],
       [0.50523822, 0.49476178],
       [0.57146332, 0.42853668],
       [0.65617537, 0.34382463],
       [0.62630419, 0.37369581],
       [0.61025304, 0.38974696],
       [0.56135797, 0.43864203],
       [0.44457135, 0.55542865],
       [0.6234743 , 0.3765257 ],
       [0.65138293, 0.34861707],
       [0.54463684, 0.45536316],
       [0.61028669, 0.38971331],
       [0.60702947, 0.39297053],
       [0.60800229, 0.39199771],
       [0.5412271 , 0.4587729 ],
       [0.63297981, 0.36702019],
       [0.52307336, 0.47692664],
       [0.56237107, 0.43762893],
       [0.54682844, 0.45317156],
       [0.54231878, 0.45768122],
       [0.57024373, 0.42975627],
       [0.54322642, 0.45677358],
       [0.65036258, 0.34963742],
       [0.66037061, 0.33962939],
       [0.51465741, 0.48534259],
       [0.55010239, 0.44989761],
       [0.513022  , 0.486978  ],
       [0.54945465, 0.45054535],
       [0.